VERSION_MAJOR	=	0
VERSION_MINOR	=	4
VERSION_PATCH	=	1
VERSION_RC		=	"beta2"

VERSION_STRING	=	"{}.{}.{}".format(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
if (VERSION_RC is not None):
	VERSION_STRING += "-{}".format(VERSION_RC)

if __name__ == "__main__":
	print(VERSION_STRING)