VERSION_MAJOR	=	0
VERSION_MINOR	=	5
VERSION_PATCH	=	0
VERSION_RC		=	0

VERSION_STRING	=	"{}.{}.{}".format(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
if (VERSION_RC is not None):
	VERSION_STRING += "-{}".format(VERSION_RC)

if __name__ == "__main__":
	print(VERSION_STRING)